### ISSUE TITLE
GeoTiff and GeoJson

### ISSUE THREAD

**Issue by NourSoltani** [VSainteuf/pytorch-psetae#13]
Hello!
I have a question about the nature of the data if you may.
In my case, I have as input data "GeoTiff" and the labels are GeoJson.
So my question here is that can I use this type of data in order to train the model, os I should use, strictly, npy and Json as data.
And if I can, Is there anything to change in the code?
Thank you!

**Comment by VSainteuf** [comment]
Hi @NourSoltani ,
The present code only supports data prepared in the same file format as the S2Agri dataset (npy).
So you can either prepare your data and store them in npy files, or rewrite your own data loader and use the rest of the code (architecture and training).

**Comment by NourSoltani** [comment]
Oh I understand.
Thank you for replying!
