### ISSUE TITLE
Order of channels

### ISSUE THREAD

**Issue by bkj** [VSainteuf/pytorch-psetae#2]
Hi -- 

Are you able to give some information about the order of channels in your pre-processed data?  I see that you're using 10 of the Sentinel-2 bands, but could you give their names and the order they appear in eg. the `S2-2017-T31TFM-PixelSet-TOY` dataset?

Thanks!

**Comment by bkj** [comment]
Also -- the values of the data are uint16's that range from 0 to 11517 -- can you give some information about the scale of these values?

**Comment by VSainteuf** [comment]
Hi!
- Regarding bands: from the 13 Sentinel-2 channels we only removed the three low resolution atmospheric bands (B01, B09 and B10). The resulting 10 channels are :
B02, B03, B04, B05, B06, B07, B08, B8A, B11, B12 (in that order)

- The L2A reflectances that we use are coded on a scale of 10,000. 
The maximum pixel value that you reported shows that some pixels have a reflectance higher than one. Such values are attained for pixels where the amount of incoming radiation is not well described by the terrain model (typically a glass roof that has a certain slope that directly reflects the sun).

Hope this helps!

**Comment by bkj** [comment]
OK great.  Is coding w/ the 10,000 scale a standard preprocessing technique, or is that something specific to this pipeline?

**Comment by VSainteuf** [comment]
16bit coding is standard as the spectral resolution of S2 is 12bit, and as for the 10,000 scale I think it's also standard. We actually retrieved the L2A sentinel tiles from [THEIA](https://www.theia-land.fr/en/products/), one of the leading French providers of L2A.

**Comment by bkj** [comment]
@VSainteuf OK thanks for the answers.  Might it be possible for you to share the preprocessing code that goes from raw L2A tiles to the data format that your model expects?  I think I understand, but I'm interested in applying your methods to a new geographic area, so I want to make sure that I'm understanding the preprocessing.

**Comment by VSainteuf** [comment]
No worries, ok I'll push the dataset preparation script to the same repo soon.  And I'd be curious to hear about your results on a different location!
