### ISSUE TITLE
How do I build my own dataset?

### ISSUE THREAD

**Issue by suojifeng** [VSainteuf/pytorch-psetae#22]
I recently read your paper and I wanted to know how to go about making my own dataset, which I found to be rather difficult

**Comment by rongtongxueya** [comment]
I have encountered the same problem, can you give me some advice? Thank you very much

**Comment by suojifeng** [comment]
> I have encountered the same problem, can you give me some advice? Thank you very much

I have recently been researching the time series remote sensing aspect, we can communicate, my qq is 1023766761
